### ISSUE TITLE
Request: Include Markdown documentations in the respository

### ISSUE THREAD

**Issue by gusbemacbe** [dolce/iziModal#121]
Hello,

I suggest you to add separated Markdown documentations to this repository because I don't have patience to open a new tab and go to your site several times, for scrolling and checking the documentations there.

**Comment by dolce** [comment]
@gusbemacbe.
Unfortunately it is too complicated to have  to update the documentation on the site and in the repository every time a new version comes out.
I used to do this in the past, but the documentation was sometimes out of sync and very extensive in the repository.
It is now more centralized and organized.

But do not you want to go to the site to read the documentation because you are lazy?
Is that serious? But you were not lazy in downloading a free project, right?
I almost do not have free time and I'm here keeping the project in the air, even without gaining anything.
I only do this out of passion, to help the community and gain knowledge.
And I ask the same of who uses. I did not force you to use it, it's here and it's free, use whoever, help whoever wants it.

I only ask that you have more caring and consideration for people and projects like this.
If you do not want to access the site, download it as a pdf, it's simple.

**Comment by gusbemacbe** [comment]
You misunderstood and misinterpreted me. You need to read attentively and carefully. I was not rude with you.

> But do not you want to go to the site to read the documentation because you are lazy?
Is that serious? But you were not lazy in downloading a free project, right?

I download the repository, but it doesn't have documentations. Because of my internet and to economise my time. My internet isn't fast to load the full page. Separated offline Markdown documentations are quick to open and load. 

> I only do this out of passion, to help the community and gain knowledge.
And I ask the same of who uses. I did not force you to use it, it's here and it's free, use whoever, help whoever wants it.

Not liking to go to your site several times  **doesn't mean** disliking your site. You need to be careful for not misinterpreting. 

> I almost do not have free time and I'm here keeping the project in the air, even without gaining anything.

You didn't gain anything because you are distributing free project and everybody thinks they do not have or need to pay you. Why didn't you become into a donationware project, use the licences CC BY-SA CC BY-ND, CC BY-NC or CC BY-NC-SA, and charge us for the commercial use and require us to atribute you? You should do it. The Animate.css, Fancybox and Slidebars developers do it and charge who uses for commercial projects. 

And moreover, to gain, sell components and templates in the sites CreativeMarket and Themeforest, and as you are specialist in JavaScript, be a partner of Alex Paduaru, @timcreative, maybe they are looking for some full stack developer (back-end and front-end) because they only design.

> I only ask that you have more caring and consideration for people and projects like this.
I have already said you in the start of this answer. You misinterpreted me.

> If you do not want to access the site, download it as a pdf, it's simple.
PDF is bad. I prefer Markdown and HTML. Thank you, I'll save and download your page. 

Next time, do not accuse anybody of nothing, or they will think something and will desconsider your project.

**Comment by dolce** [comment]
I did not accuse you of anything, you just said that you did not have the patience to access the site. You, not me.
I did not make any money because I opted to leave the project open, as I said earlier the reasons. Donate whoever, use whoever.
It was all interpreted according to what you wrote.

Next time, do not be rude, among thousands of iziModal and iziToast downloads, you were the one to act like that, enjoy what you have for free, and think you should improve? Contribute, it is open to all!
**Good luck!**

**Comment by dolce** [comment]
I did not accuse you of anything, you just said that you did not have the patience to open a new tab, access the site, and scroll the screen. You, not me.
I did not make any money because I opted to leave the project open, as I said earlier the reasons. Donate whoever, use whoever.
It was all interpreted according to what you wrote.

Next time, do not be rude, among thousands of iziModal and iziToast downloads, you were the one to act like that, enjoy what you have for free, and think you should improve? Contribute, it is open to all!
**Good luck!**
