### ISSUE TITLE
Is it AMD compatible ? 

### ISSUE THREAD

**Issue by rakibulalam** [dolce/iziModal#75]
I try a lot to use it my recent project module and also try to convert the plugin to AMD format!! Unfortunately, the plugin is showing undefined and not working :( ++

**Comment by dolce** [comment]
Hello @rakibulalam. Firstly, thank you for your comment.
I'm now working on the new version of iziModal (v1.5.0). And I'd like you to test AMD support. Can be?

**Comment by dolce** [comment]
[iziModal-v1.5.0.zip](https://github.com/dolce/iziModal/files/873882/iziModal-v1.5.0.zip)
Try to use this version and give me your feedback.

**Comment by jungleBadger** [comment]
Hey Marcelo, how are you? I'm following up this one cause I'm trying to use your package as AMD as well. I achieved to import the lib through require and browserify routine but the catchy is that iziModal requires jQuery exposed as a global property and I'm bundling everything together (including jQuery).

I've changed the code you provided a bit in order to get that working on my use case and I'm attaching it here.

By the way, thanks very much for this lib I tried to use it on another project but failed on requiring issue. Now with a little bit more time I get back to it and you helped a lot as well. :)

[iziModal-require.zip](https://github.com/dolce/iziModal/files/885855/iziModal-require.zip)

**Comment by dolce** [comment]
Hello @jungleBadger , thank you for your contribution.
Have you been successful in this version you submitted(iziModal-require.zip)?

**Comment by jungleBadger** [comment]
Hey Marcelo, in fact I did but I've found an issue with the stopLoading method (the modal is not being removed, I've started debugging but not finished yet, had to move on to another task).

But the modal is being imported correctly and rendered just fine, this is my setup after changing the code:

    var $ = require("jquery"),
        iziModal = require("../../assets/shared_libs/iziModal/iziModal")($);

    var modalInstance = $("#modal").iziModal();

**Comment by dolce** [comment]
Thansk! I'll check

**Comment by dolce** [comment]
@jungleBadger, é BR né? pode me add no face? Queria fazer novos testes nessas alterações, vlw!
https://www.facebook.com/dolcemarcelo
